baseurl = "https://yadong.site/"
languageCode = "en-us"
title = "Yadong Liu | 刘亚东"
theme = "hugo-xmin"
disqusShortname = "yadong1990"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
[[menu.main]]
    name = "Publication"
    url = "/publication/"
    weight = 4
[[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 5


[params]
    description = "Personal website of Yadong Liu; 刘亚东的个人网站"
    footer = "&copy; 2019 Yadong Liu"
    
[[params.logo]]
    img = "/img/dong.png"
    alt = "Yadong Liu"
