baseurl: https://liuyadong.github.io/
title: Yadong Liu | 刘亚东
languageCode: en-us
hasCJKLanguage: yes
enableEmoji: yes
disqusShortname: yadong1990
footnotereturnlinkcontents: ↩
theme: hugo-xmin
publishDir: docs/
taxonomies:
  tag: tags
permalinks:
  blog: /blog/:year-:month-:day-:slug/
ignoreFiles:
  - \\.Rmd$
  - \\.Rmarkdown$
  - _cache$
  - \\.knit\\.md$
  - \\.utf8\\.md$
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog/
      weight: 2
    - name: Publications
      url: /publications/
      weight: 3
    - name: Slides
      url: /slides/
      weight: 4
    - name: Software
      url: /software/
      weight: 5
params:
  description: Personal website of Yadong Liu; 刘亚东的个人网站
  footer: '&copy; [Yadong Liu](/) 2018 - 2024'

markup:
  goldmark:
    renderer:
      unsafe: true
