baseurl = "/liuyadong.xyz/"
languageCode = "en-us"
title = "Yadong Liu | 刘亚东"
theme = "hugo-xmin"
disqusShortname = "yadong1990"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Post"
    url = "/post/"
    weight = 2

[params]
    description = "Personal website of Yadong Liu; 刘亚东的个人网站"
    footer = "&copy; [Yadong Liu](/) 2018 - 2019"
    
[[params.logo]]
    img = "/img/dong.png"
    alt = "Yadong Liu"
