baseurl = "https://liuyadong.github.io/"
languageCode = "en-us"
title = "Yadong Liu | 刘亚东"
theme = "hugo-xmin"
disqusShortname = "yadong1990"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
publishDir = "docs/"

[permalinks]
    blog = "/blog/:year-:month-:day-:slug/"

[taxonomies]
    tag = "tags"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
[[menu.main]]
    name = "Slides"
    url = "/slides/"
    weight = 4
[[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 5

[params]
    description = "Personal website of Yadong Liu; 刘亚东的个人网站"
    footer = "&copy; [Yadong Liu](/) 2018 - 2020"
