baseurl: https://liuyadong.github.io/
disqusShortname: yadong1990
enableEmoji: yes
footnotereturnlinkcontents: ↩
hasCJKLanguage: yes
ignoreFiles:
  - \\.Rmd$
  - \\.Rmarkdown$
  - _cache$
  - \\.knit\\.md$
  - \\.utf8\\.md$
languageCode: en-us
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog/
      weight: 2
    - name: Publications
      url: /publications/
      weight: 3
    - name: Slides
      url: /slides/
      weight: 4
    - name: Software
      url: /software/
      weight: 5
params:
  description: Personal website of Yadong Liu; 刘亚东的个人网站
  footer: '&copy; [Yadong Liu](/) 2018 - 2020'
permalinks:
  blog: /blog/:year-:month-:day-:slug/
publishDir: docs/
taxonomies:
  tag: tags
theme: hugo-xmin
title: Yadong Liu | 刘亚东
